version: "3"

services:
    api_uts:
        build: .
        image: api_uts:v1.0
        container_name: api_uts
        restart: always
        # env_file:
        #     - .env
        command: python manage.py runserver 0.0.0.0:8001
        volumes:
            - .:/code
        ports:
            - 8001:8001
volumes:
    .:
